# Generated by Django 4.0.4 on 2022-05-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_age_user_calories_user_experience_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.IntegerField(choices=[(1, 'Weight loss'), (2, 'Weight gain'), (3, 'Maintainance')], default=1, null=True),
        ),
    ]
