# Generated by Django 4.0.4 on 2022-05-22 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerreview',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_under_review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
